#include "hal_data.h"
#include "stdio.h"

volatile bool uart9BusyFlag = 0;

int _write(int fd, char *pBuffer, int size)
{
    uart9BusyFlag = 1;
    R_SCI_UART_Write(&g_uart9_ctrl, pBuffer, size);
    while(uart9BusyFlag);
    return size;
}

void my_drawHline(uint16_t x, uint16_t y, uint16_t len){
    uint16_t* buffer = (uint16_t*)fb_background;
    for(uint16_t i=0; i<len; i++){
        if(i+x < 480){
            buffer[y*480 + x + i] = 0xe007;
        }else {
            break;
        }
    }
}

void my_uart_irq(uart_callback_args_t *p_args)
{
    if(p_args->event == UART_EVENT_TX_COMPLETE){
        uart9BusyFlag = 0;
    }
}

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
    uint8_t a = 0;

    R_SCI_UART_Open(&g_uart9_ctrl, &g_uart9_cfg);

    R_GPT_Open(&g_timer5_ctrl, &g_timer5_cfg);
    R_GPT_Start(&g_timer5_ctrl);

    R_GLCDC_Open(&g_display0_ctrl, &g_display0_cfg);
    R_GLCDC_Start(&g_display0_ctrl);

    uint16_t* u16buff = (uint16_t*)fb_background;

    my_drawHline(100,50,50);

    while(1){
        R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_02_PIN_09, 1);
        R_BSP_SoftwareDelay(500, BSP_DELAY_UNITS_MILLISECONDS);
        R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_02_PIN_09, 0);
        R_BSP_SoftwareDelay(500, BSP_DELAY_UNITS_MILLISECONDS);

        R_BSP_PinAccessEnable();
        R_BSP_PinWrite(BSP_IO_PORT_02_PIN_10, 1);
        R_BSP_PinAccessDisable();
        R_BSP_SoftwareDelay(500, BSP_DELAY_UNITS_MILLISECONDS);
        R_BSP_PinAccessEnable();
        R_BSP_PinWrite(BSP_IO_PORT_02_PIN_10, 0);
        R_BSP_PinAccessDisable();
        R_BSP_SoftwareDelay(500, BSP_DELAY_UNITS_MILLISECONDS);
        R_GPT_DutyCycleSet(&g_timer5_ctrl, (a & 0x01)?60000:120000, GPT_IO_PIN_GTIOCB);

        for(int i=0; i<480*272; i++){
            u16buff[i] = 0xf800;
        }
        R_BSP_SoftwareDelay(500, BSP_DELAY_UNITS_MILLISECONDS);
        printf("%d\n",a++);
        for(int i=0; i<480*272; i++){
            u16buff[i] = 0xe007;
        }
//        printf("%d\n",a++);
        R_BSP_SoftwareDelay(500, BSP_DELAY_UNITS_MILLISECONDS);


    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, &IOPORT_CFG_NAME);
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
